"""Grader for competitive/cp01_range_query. Tests the public contract only (see TASK.md).

Validity invariant: PASSES on the gold reference, FAILS on the broken reference.

The broken variant uses a naive O(n) per-operation loop that is correct on small
inputs but times out on the hard complexity gate.

Test catalogue (>=10 required for competitive):
  1.  test_empty_ops              — no operations → empty list
  2.  test_all_add_no_sum         — only add ops → empty list
  3.  test_single_element         — n=1, boundary l==r
  4.  test_simple_example         — the TASK.md walkthrough example
  5.  test_boundary_lr_equal      — l == r (point update + point sum)
  6.  test_full_range             — add to full range, sum full range
  7.  test_negative_values        — v < 0 (net subtractions)
  8.  test_overlapping_adds       — multiple overlapping range adds
  9.  test_interleaved_ops        — add then sum alternating
  10. test_correctness_vs_ref     — random small ops vs brute-force reference
  11. test_adversarial_ranges     — interleaved overlapping adds then sums (correctness)
  12. adversarial_hard_gate       — n=200000, q~200000, fixed seed; MUST complete in 10 s
  13. test_soft_complexity        — empirical curve fit (advisory; fails only >2 tiers off)
  14. test_code_quality           — advisory only (never asserted)
"""
from __future__ import annotations

import json
import random
from pathlib import Path

import pytest

from _lib import grading_utils as gu

CATEGORY, TASK_ID = "competitive", "cp01_range_query"
SOL = gu.require_solution_dir(CATEGORY, TASK_ID)
process_queries = gu.load_callable(SOL, "solution.py", "process_queries")

# Oracle-grounded mutation corpus (hidden under expected/, never shown to the
# agent). Every input's expected output was decided by a brute-force array
# simulation — an independent oracle — and verified equal to the gold; every
# input also kills >=1 real wrong solution (a mutation of the gold, a
# hand-written common mistake, or the __broken reference). Generated by
# experiment_mihaco/mutation_gen/gen_cp01_range_query.py.
_CORPUS = json.loads(
    (Path(__file__).resolve().parents[1] / "expected" / "mutation_corpus.json").read_text()
)

# Fixed seed for all deterministic random data in this grader.
_RNG = random.Random(42)

# ---------------------------------------------------------------------------
# Reference implementation (brute-force O(n*q)) — used ONLY in the grader for
# small-input correctness checks. It is never imported from a solution.
# ---------------------------------------------------------------------------

def _reference(n: int, ops: list[tuple]) -> list[int]:
    arr = [0] * n
    out: list[int] = []
    for op in ops:
        if op[0] == "add":
            _, l, r, v = op
            for i in range(l, r + 1):
                arr[i] += v
        else:
            _, l, r = op
            out.append(sum(arr[l : r + 1]))
    return out


# ---------------------------------------------------------------------------
# 1  Empty ops
# ---------------------------------------------------------------------------

def test_empty_ops():
    """No operations — result must be an empty list."""
    result = process_queries(10, [])
    assert result == [], f"expected [], got {result!r}"


# ---------------------------------------------------------------------------
# 2  All add, no sum
# ---------------------------------------------------------------------------

def test_all_add_no_sum():
    """Only add operations — no sum → empty result list."""
    ops = [("add", 0, 4, 1), ("add", 1, 3, 2), ("add", 2, 2, 5)]
    result = process_queries(5, ops)
    assert result == [], f"expected [], got {result!r}"


# ---------------------------------------------------------------------------
# 3  Single element (n=1, l==r boundary)
# ---------------------------------------------------------------------------

def test_single_element():
    """n=1: one cell, add then query."""
    ops = [
        ("add", 0, 0, 7),
        ("sum", 0, 0),
        ("add", 0, 0, -3),
        ("sum", 0, 0),
    ]
    result = process_queries(1, ops)
    assert result == [7, 4], f"expected [7, 4], got {result!r}"


# ---------------------------------------------------------------------------
# 4  Simple example from TASK.md
# ---------------------------------------------------------------------------

def test_simple_example():
    """Walkthrough example from TASK.md."""
    ops = [
        ("add", 0, 4, 1),   # [1, 1, 1, 1, 1]
        ("sum", 0, 4),       # 5
        ("add", 1, 3, 2),   # [1, 3, 3, 3, 1]
        ("sum", 1, 3),       # 9
        ("sum", 0, 0),       # 1
    ]
    result = process_queries(5, ops)
    assert result == [5, 9, 1], f"expected [5, 9, 1], got {result!r}"


# ---------------------------------------------------------------------------
# 5  Boundary l==r (point update + point query)
# ---------------------------------------------------------------------------

def test_boundary_lr_equal():
    """Point update at a single index, then query that point and its neighbors."""
    n = 8
    ops = [
        ("add", 3, 3, 100),
        ("sum", 3, 3),   # 100
        ("sum", 2, 4),   # 100  (neighbors are still 0)
        ("sum", 0, 7),   # 100
        ("sum", 4, 4),   # 0
    ]
    result = process_queries(n, ops)
    assert result == [100, 100, 100, 0], f"expected [100, 100, 100, 0], got {result!r}"


# ---------------------------------------------------------------------------
# 6  Full-range add then full-range sum
# ---------------------------------------------------------------------------

def test_full_range():
    """Add v to every element, then sum the full array."""
    n = 6
    v = 3
    ops = [
        ("add", 0, n - 1, v),
        ("sum", 0, n - 1),   # n * v = 18
    ]
    result = process_queries(n, ops)
    assert result == [n * v], f"expected [{n * v}], got {result!r}"


# ---------------------------------------------------------------------------
# 7  Negative values
# ---------------------------------------------------------------------------

def test_negative_values():
    """v can be negative; net result may be negative too."""
    n = 5
    ops = [
        ("add", 0, 4, 10),   # [10, 10, 10, 10, 10]
        ("add", 1, 3, -15),  # [10, -5, -5, -5, 10]
        ("sum", 0, 4),        # 5
        ("sum", 1, 3),        # -15
        ("sum", 2, 2),        # -5
    ]
    expected = _reference(n, ops)
    result = process_queries(n, ops)
    assert result == expected, f"expected {expected}, got {result!r}"


# ---------------------------------------------------------------------------
# 8  Multiple overlapping range adds
# ---------------------------------------------------------------------------

def test_overlapping_adds():
    """Overlapping range adds accumulate correctly."""
    n = 10
    ops = [
        ("add", 0, 9, 1),    # all +1
        ("add", 2, 7, 2),    # middle +2
        ("add", 4, 5, 4),    # center +4
        ("sum", 0, 9),       # depends on accumulation
        ("sum", 4, 5),
        ("sum", 0, 1),
        ("sum", 8, 9),
    ]
    expected = _reference(n, ops)
    result = process_queries(n, ops)
    assert result == expected, f"expected {expected}, got {result!r}"


# ---------------------------------------------------------------------------
# 9  Interleaved operations
# ---------------------------------------------------------------------------

def test_interleaved_ops():
    """Add and sum alternate — verify running state is maintained."""
    n = 7
    ops = [
        ("add", 0, 6, 1),
        ("sum", 0, 6),        # 7
        ("add", 0, 3, 10),
        ("sum", 0, 3),        # 4*(1+10) = 44
        ("sum", 4, 6),        # 3
        ("add", 2, 5, -5),
        ("sum", 0, 6),        # 1+11+6+6+1+1-5 ... use reference
    ]
    expected = _reference(n, ops)
    result = process_queries(n, ops)
    assert result == expected, f"expected {expected}, got {result!r}"


# ---------------------------------------------------------------------------
# 10  Correctness vs brute-force reference (random small ops)
# ---------------------------------------------------------------------------

def test_correctness_vs_ref():
    """Randomly generated small instances compared against brute-force reference."""
    rng = random.Random(99)
    for trial in range(20):
        n = rng.randint(2, 50)
        ops = []
        for _ in range(100):
            l = rng.randint(0, n - 1)
            r = rng.randint(l, n - 1)
            if rng.random() < 0.5:
                v = rng.randint(-100, 100)
                ops.append(("add", l, r, v))
            else:
                ops.append(("sum", l, r))
        expected = _reference(n, ops)
        got = process_queries(n, ops)
        assert got == expected, (
            f"trial {trial}: n={n}, expected {expected[:5]}..., got {got[:5]}..."
        )


# ---------------------------------------------------------------------------
# 11  Adversarial: interleaved overlapping range-adds then range-sums
# ---------------------------------------------------------------------------

def test_adversarial_ranges():
    """Correctness under dense, interleaved, overlapping operations on a moderate array."""
    rng = random.Random(7)
    n = 1000
    ops = []
    # Build a mix of overlapping adds and targeted sums
    for _ in range(500):
        l1 = rng.randint(0, n - 1)
        r1 = rng.randint(l1, min(l1 + 200, n - 1))
        v = rng.randint(-50, 50)
        ops.append(("add", l1, r1, v))
        l2 = rng.randint(0, n - 1)
        r2 = rng.randint(l2, min(l2 + 300, n - 1))
        ops.append(("sum", l2, r2))

    expected = _reference(n, ops)
    got = process_queries(n, ops)
    assert got == expected, (
        f"adversarial_ranges mismatch: first diff at index "
        f"{next(i for i,(a,b) in enumerate(zip(got,expected)) if a!=b)}"
        if got != expected else ""
    )


# ---------------------------------------------------------------------------
# 12  HARD time gate (adversarial large input, fixed seed 1337)
#     The broken O(n*q) naive solution MUST time out here.
#     A correct O((n+q) log n) solution (dual Fenwick BIT OR lazy segment
#     tree) MUST complete within 10 seconds.
# ---------------------------------------------------------------------------

def test_adversarial_hard_gate():
    """n=200000, q~200000 interleaved ops — must complete within 10 seconds.

    Seed: random.Random(1337).  An O(n*q) naive solution needs ~2x10^10
    iterations (many minutes). Both an O((n+q) log n) dual-Fenwick BIT and a
    lazy-propagation segment tree finish well inside the 10 s budget; the
    budget is deliberately generous so a correct segtree is not a false
    negative on slower hardware.
    """
    SEED = 1337
    n = 200_000
    q = 200_000
    rng = random.Random(SEED)

    ops = []
    for _ in range(q):
        l = rng.randint(0, n - 1)
        r = rng.randint(l, n - 1)
        if rng.random() < 0.5:
            v = rng.randint(-1000, 1000)
            ops.append(("add", l, r, v))
        else:
            ops.append(("sum", l, r))

    result = gu.run_within(10.0, process_queries, n, ops)
    # Must return a list of ints
    assert isinstance(result, list), f"expected list, got {type(result)}"
    assert all(isinstance(x, int) for x in result), "all sum results must be int"


# ---------------------------------------------------------------------------
# 13  SOFT complexity signal (advisory; fails only if >2 tiers worse than O(n log n))
# ---------------------------------------------------------------------------

@pytest.mark.soft_complexity
def test_soft_complexity():
    """Empirical time-complexity check — advisory only."""
    rng_outer = random.Random(2024)

    def make_input(n: int):
        rng = random.Random(n)
        ops = []
        for _ in range(n):
            l = rng.randint(0, n - 1)
            r = rng.randint(l, n - 1)
            if rng.random() < 0.5:
                ops.append(("add", l, r, rng.randint(-100, 100)))
            else:
                ops.append(("sum", l, r))
        return (n, ops)

    sizes = [500, 1000, 2000, 4000, 8000]
    timings = gu.measure_runtime(make_input, lambda args: process_queries(*args), sizes)
    report = gu.estimate_time_complexity(timings)
    label = report["label"]
    print(f"[soft_complexity] estimated={label}  target=O(n log n)  ranked={report['ranked'][:3]}")
    assert gu.within_one_tier(label, "O(n log n)"), (
        f"soft complexity check: estimated {label} is more than one tier above O(n log n)."
    )


# ---------------------------------------------------------------------------
# Mutation corpus — oracle-grounded, mutation-seeded discriminating test cases
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("case", _CORPUS["cases"], ids=range(len(_CORPUS["cases"])))
def test_mutation_corpus(case):
    """Replay the oracle-grounded, mutation-seeded corpus.

    Expected outputs come from a brute-force array simulation (independent
    oracle), cross-validated against the gold; each input discriminates a real
    wrong solution. A subtly-incorrect candidate that slips past the curated
    tests is caught here by an empirically-discovered killing input.

    JSON turns tuples into lists — convert each op back to a tuple before calling.
    """
    n, ops_raw = case["args"]
    ops = [tuple(o) for o in ops_raw]
    assert process_queries(n, ops) == case["expected"]


# ---------------------------------------------------------------------------
# 14  Advisory code-quality report (never asserted)
# ---------------------------------------------------------------------------

@pytest.mark.code_quality
def test_code_quality():
    rep = gu.code_quality_report(SOL)
    print("code_quality:", rep)   # advisory only — never a gate
