"""Grader for competitive/cp04_tree_distance. Tests the public contract only (see TASK.md).

Validity invariant: PASSES on the gold reference, FAILS on the broken reference.

Test catalogue (>=10 required for competitive):
  1.  test_single_node           — n=1, no edges -> [0]
  2.  test_two_nodes             — n=2, single edge weight 3
  3.  test_path_unweighted       — path 0-1-2 with unit weights
  4.  test_path_weighted         — path 0-1-2 with weights 1 and 2
  5.  test_star_unweighted       — star center=0, 3 leaves, unit weights
  6.  test_star_weighted         — star with varying edge weights
  7.  test_balanced_tree         — 7-node complete binary tree, unit weights
  8.  test_asymmetric_weights    — mixed topology with asymmetric weights
  9.  test_large_star            — star with n=100 leaves (checks rerooting identity)
  10. test_caterpillar_medium    — caterpillar/path n=1000 (medium adversarial)
  11. adversarial_time_gate      — n=200000, fixed-seed random tree, timeout 15s
  12. test_soft_complexity       — empirical curve fit (soft, only fails >2 tiers off)
  13. test_code_quality          — advisory only (never asserted)
"""
from __future__ import annotations

import heapq
import json
import random
from pathlib import Path

import pytest

from _lib import grading_utils as gu

CATEGORY, TASK_ID = "competitive", "cp04_tree_distance"
SOL = gu.require_solution_dir(CATEGORY, TASK_ID)
sum_of_distances = gu.load_callable(SOL, "solution.py", "sum_of_distances")

# Oracle-grounded mutation corpus (hidden under expected/, never shown to the
# agent). Every input's expected output was decided by an independent all-pairs
# Dijkstra oracle and verified equal to the gold; every input also kills >=1
# real wrong solution (a mutation of the gold, a hand-written common mistake,
# or the __broken reference). Generated by
# experiment_mihaco/mutation_gen/gen_cp04.py.
_CORPUS = json.loads(
    (Path(__file__).resolve().parents[1] / "expected" / "mutation_corpus.json").read_text()
)


# ---------------------------------------------------------------------------
# Reference implementation: O(n^2) Dijkstra from each node (correct, used
# for verifying small cases inside the grader).
# ---------------------------------------------------------------------------

def _reference_sum_of_distances(n: int, edges: list[tuple]) -> list[int]:
    """Naive O(n^2 log n) reference — correct but slow; used for small n only."""
    if n == 1:
        return [0]
    adj: list[list[tuple[int, int]]] = [[] for _ in range(n)]
    for u, v, w in edges:
        adj[u].append((v, w))
        adj[v].append((u, w))

    def dijkstra_sum(src: int) -> int:
        dist = [float("inf")] * n
        dist[src] = 0
        heap = [(0, src)]
        while heap:
            d, u = heapq.heappop(heap)
            if d > dist[u]:
                continue
            for v, w in adj[u]:
                nd = d + w
                if nd < dist[v]:
                    dist[v] = nd
                    heapq.heappush(heap, (nd, v))
        return int(sum(d for d in dist if d != float("inf")))

    return [dijkstra_sum(i) for i in range(n)]


# ---------------------------------------------------------------------------
# Helper: build a random tree with fixed seed
# ---------------------------------------------------------------------------

def _random_tree(n: int, seed: int, max_w: int = 100) -> list[tuple]:
    """Build a random tree on n nodes with given seed. Returns list of (u,v,w)."""
    rng = random.Random(seed)
    edges = []
    for v in range(1, n):
        u = rng.randint(0, v - 1)
        w = rng.randint(1, max_w)
        edges.append((u, v, w))
    return edges


# ---------------------------------------------------------------------------
# 1. n=1 — single node
# ---------------------------------------------------------------------------

def test_single_node():
    result = sum_of_distances(1, [])
    assert result == [0], f"expected [0], got {result}"


# ---------------------------------------------------------------------------
# 2. n=2 — single edge
# ---------------------------------------------------------------------------

def test_two_nodes():
    result = sum_of_distances(2, [(0, 1, 3)])
    assert result == [3, 3], f"expected [3, 3], got {result}"


# ---------------------------------------------------------------------------
# 3. Path 0-1-2 with unit weights
# ---------------------------------------------------------------------------

def test_path_unweighted():
    # 0 --1-- 1 --1-- 2
    # res[0] = 1+2 = 3; res[1] = 1+1 = 2; res[2] = 2+1 = 3
    edges = [(0, 1, 1), (1, 2, 1)]
    result = sum_of_distances(3, edges)
    expected = _reference_sum_of_distances(3, edges)
    assert result == expected, f"expected {expected}, got {result}"


# ---------------------------------------------------------------------------
# 4. Path 0-1-2 with non-uniform weights
# ---------------------------------------------------------------------------

def test_path_weighted():
    # 0 --1-- 1 --2-- 2
    # res[0] = 1+3 = 4; res[1] = 1+2 = 3; res[2] = 3+2 = 5
    edges = [(0, 1, 1), (1, 2, 2)]
    result = sum_of_distances(3, edges)
    expected = _reference_sum_of_distances(3, edges)
    assert result == expected, f"expected {expected}, got {result}"
    assert result == [4, 3, 5], f"exact check failed: {result}"


# ---------------------------------------------------------------------------
# 5. Star graph, unit weights
# ---------------------------------------------------------------------------

def test_star_unweighted():
    # Star: center=0, leaves=1,2,3,4 all weight 1
    # res[0] = 4; res[leaf] = 1 + 1*3 + 1*3... actually:
    # res[1] = dist(1,0)+dist(1,2)+dist(1,3)+dist(1,4) = 1+2+2+2 = 7 (wait n=5 here)
    n = 5
    edges = [(0, i, 1) for i in range(1, n)]
    result = sum_of_distances(n, edges)
    expected = _reference_sum_of_distances(n, edges)
    assert result == expected, f"expected {expected}, got {result}"
    # center: sum = 4*1 = 4
    assert result[0] == 4, f"center should have distance sum 4, got {result[0]}"
    # each leaf: 1 (to center) + 2*(n-2) (to other leaves via center)
    for i in range(1, n):
        expected_leaf = 1 + 2 * (n - 2)
        assert result[i] == expected_leaf, f"leaf {i} expected {expected_leaf}, got {result[i]}"


# ---------------------------------------------------------------------------
# 6. Star with varying edge weights
# ---------------------------------------------------------------------------

def test_star_weighted():
    # center=0, leaves: (0,1,2), (0,2,3), (0,3,5)
    n = 4
    edges = [(0, 1, 2), (0, 2, 3), (0, 3, 5)]
    result = sum_of_distances(n, edges)
    expected = _reference_sum_of_distances(n, edges)
    assert result == expected, f"expected {expected}, got {result}"


# ---------------------------------------------------------------------------
# 7. Balanced binary tree with 7 nodes, unit weights
# ---------------------------------------------------------------------------

def test_balanced_tree():
    # Perfect binary tree: 0->1,2; 1->3,4; 2->5,6
    edges = [(0, 1, 1), (0, 2, 1), (1, 3, 1), (1, 4, 1), (2, 5, 1), (2, 6, 1)]
    n = 7
    result = sum_of_distances(n, edges)
    expected = _reference_sum_of_distances(n, edges)
    assert result == expected, f"expected {expected}, got {result}"


# ---------------------------------------------------------------------------
# 8. Asymmetric weights on mixed topology
# ---------------------------------------------------------------------------

def test_asymmetric_weights():
    # Tree: 0-(10)->1; 1-(1)->2; 1-(100)->3; 2-(5)->4
    edges = [(0, 1, 10), (1, 2, 1), (1, 3, 100), (2, 4, 5)]
    n = 5
    result = sum_of_distances(n, edges)
    expected = _reference_sum_of_distances(n, edges)
    assert result == expected, f"expected {expected}, got {result}"


# ---------------------------------------------------------------------------
# 9. Large star n=100 — checks rerooting formula at scale for small n
# ---------------------------------------------------------------------------

def test_large_star():
    n = 100
    rng = random.Random(7)
    edges = [(0, i, rng.randint(1, 20)) for i in range(1, n)]
    result = sum_of_distances(n, edges)
    expected = _reference_sum_of_distances(n, edges)
    assert result == expected, "large star: mismatch vs reference"


# ---------------------------------------------------------------------------
# 10. Caterpillar/path tree n=1000 — medium adversarial (checks iterative DFS)
# ---------------------------------------------------------------------------

def test_caterpillar_medium():
    """Path (spine) of length 500 with one leaf per spine node."""
    spine = 500
    n = spine * 2  # 1000 nodes: 0..499 spine, 500..999 leaves
    # Build spine: 0-1-2-...-499
    edges = [(i, i + 1, 1) for i in range(spine - 1)]
    # Attach one leaf to each spine node
    for i in range(spine):
        edges.append((i, spine + i, 2))
    result = sum_of_distances(n, edges)
    expected = _reference_sum_of_distances(n, edges)
    assert result == expected, "caterpillar medium: mismatch vs reference"


# ---------------------------------------------------------------------------
# 11. ADVERSARIAL hard time gate: n=200000, fixed seed, timeout=15s
# ---------------------------------------------------------------------------

@pytest.mark.adversarial
def test_adversarial_time_gate():
    """n=200000 random tree (fixed seed), must complete within 15 seconds.

    The O(n) rerooting DP finishes well within the budget.
    The O(n^2) naive approach (Dijkstra from each node) would require
    ~2 × 10^10 steps and takes many minutes — it TIMES OUT here.
    """
    n = 200_000
    edges = _random_tree(n, seed=42, max_w=100)
    result = gu.run_within(15.0, sum_of_distances, n, edges)
    # Basic sanity: correct length, non-negative integers
    assert isinstance(result, list), "result must be a list"
    assert len(result) == n, f"expected {n} elements, got {len(result)}"
    assert all(isinstance(x, int) and x >= 0 for x in result), \
        "all elements must be non-negative integers"
    # Spot-check a few nodes against reference on a small subtree
    # (build same tree n=10 with same initial edges for sanity)
    n_small = 50
    edges_small = _random_tree(n_small, seed=42, max_w=100)
    ref_small = _reference_sum_of_distances(n_small, edges_small)
    result_small = sum_of_distances(n_small, edges_small)
    assert result_small == ref_small, "spot check on small instance failed"


# ---------------------------------------------------------------------------
# 12. SOFT complexity signal
# ---------------------------------------------------------------------------

@pytest.mark.soft_complexity
def test_soft_complexity():
    """Empirical time-complexity estimate -- advisory; fails only if >2 tiers off O(n).

    Sizes are kept small so even an O(n^2) submission can complete during the
    grader run; the hard gate (test_adversarial_time_gate) is the real
    complexity discriminator.  The soft check only rejects algo far worse than
    O(n^2) (e.g. O(n^3) or exponential).
    """
    # Sizes small enough that O(n^2) finishes in < 0.5s per size
    sizes = [100, 200, 300, 400, 500]

    def make_input(n: int):
        return (n, _random_tree(n, seed=n, max_w=10))

    timings = gu.measure_runtime(
        make_input,
        lambda args: sum_of_distances(args[0], args[1]),
        sizes,
        repeats=2,
    )
    report = gu.estimate_time_complexity(timings)
    label = report["label"]
    print(f"[soft_complexity] estimated={label}  target=O(n)  ranked={report['ranked'][:3]}")
    # Allow up to O(n^2) — two tiers above O(n) — before failing.
    # The adversarial gate is the real discriminator.
    assert gu.within_one_tier(label, "O(n^2)"), (
        f"soft complexity check: estimated {label} is more than one tier above O(n^2). "
        "This is a strong signal of an incorrect (or worse-than-quadratic) algorithm."
    )


# ---------------------------------------------------------------------------
# 13. Advisory code-quality report (never asserted)
# ---------------------------------------------------------------------------

@pytest.mark.code_quality
def test_code_quality():
    rep = gu.code_quality_report(SOL)
    print("code_quality:", rep)   # advisory only — never a gate


# ---------------------------------------------------------------------------
# 14.  Oracle-grounded mutation corpus
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("case", _CORPUS["cases"], ids=range(len(_CORPUS["cases"])))
def test_mutation_corpus(case):
    """Replay the oracle-grounded, mutation-seeded corpus.

    Expected outputs come from an independent all-pairs Dijkstra oracle,
    cross-validated against the gold; each input discriminates a real wrong
    solution. A subtly-incorrect candidate that slips past the curated tests is
    caught here by an empirically-discovered killing input.
    """
    n, raw_edges = case["args"]
    edges = [tuple(e) for e in raw_edges]
    assert sum_of_distances(n, edges) == case["expected"]
