"""Grader for competitive/cp03_string_period. Tests the public contract only (see TASK.md).

Validity invariant: PASSES on the gold reference, FAILS on the broken reference
(the broken variant is a naive O(n*m) scan that times out on the adversarial gate).

Test catalogue (>=10 required for competitive):
  1.  test_empty_pattern              — empty pattern → []
  2.  test_pattern_longer_than_text   — len(pattern) > len(text) → []
  3.  test_no_match                   — no occurrences in text
  4.  test_single_match_start         — match at position 0
  5.  test_single_match_end           — match at end of text
  6.  test_multiple_matches           — two non-overlapping matches
  7.  test_overlapping_matches        — overlapping: 'aaaa'/'aa' → [0,1,2]
  8.  test_single_wildcard            — '?' matches one arbitrary char
  9.  test_all_wildcard_pattern       — pattern all '?' of same length as text
  10. test_match_start_and_end        — matches at index 0 and last valid index
  11. test_wildcard_at_boundaries     — '?b?' matches at positions where b is mid
  12. test_single_char_text_and_pat   — one-char text, one-char pattern
  13. adversarial_complexity_gate     — HARD gate: text='a'*1_000_000, pattern='a'*499+'?'
                                        naive O(n*m) times out; KMP/Z-algo passes
  14. test_soft_complexity            — empirical O(n+m) estimate (soft signal)
  15. test_code_quality               — advisory only (never asserted)
"""
from __future__ import annotations

import pytest

from _lib import grading_utils as gu

import json
from pathlib import Path

CATEGORY, TASK_ID = "competitive", "cp03_string_period"
SOL = gu.require_solution_dir(CATEGORY, TASK_ID)
count_pattern = gu.load_callable(SOL, "solution.py", "count_pattern")

# Oracle-grounded mutation corpus (hidden under expected/, never shown to the
# agent). Every input's expected output was decided by Python's stdlib `re`
# engine — an external, independent oracle — and verified equal to the gold;
# every input also kills >=1 real wrong solution (a mutation of the gold, a
# hand-written common mistake, or the __broken reference). Generated by
# experiment_mihaco/mutation_gen/gen_cp03.py.
_CORPUS = json.loads(
    (Path(__file__).resolve().parents[1] / "expected" / "mutation_corpus.json").read_text()
)


# ---------------------------------------------------------------------------
# Small reference implementation used only in the grader for cross-checking
# ---------------------------------------------------------------------------

def _naive(text: str, pattern: str) -> list[int]:
    """Naive O(n*m) reference — only used on small inputs in this grader."""
    n, m = len(text), len(pattern)
    if m == 0 or m > n:
        return []
    results = []
    for i in range(n - m + 1):
        if all(p == '?' or p == t for p, t in zip(pattern, text[i:i + m])):
            results.append(i)
    return results


# ---------------------------------------------------------------------------
# 1  Empty pattern → []
# ---------------------------------------------------------------------------

def test_empty_pattern():
    assert count_pattern("hello world", "") == []
    assert count_pattern("", "") == []


# ---------------------------------------------------------------------------
# 2  Pattern longer than text → []
# ---------------------------------------------------------------------------

def test_pattern_longer_than_text():
    assert count_pattern("ab", "abc") == []
    assert count_pattern("", "a") == []


# ---------------------------------------------------------------------------
# 3  No match
# ---------------------------------------------------------------------------

def test_no_match():
    result = count_pattern("abcdef", "xyz")
    assert result == [], f"expected [], got {result}"
    result2 = count_pattern("aababab", "aaa")
    assert result2 == _naive("aababab", "aaa")


# ---------------------------------------------------------------------------
# 4  Match at start of text
# ---------------------------------------------------------------------------

def test_single_match_start():
    result = count_pattern("abcdef", "abc")
    assert result == [0], f"expected [0], got {result}"


# ---------------------------------------------------------------------------
# 5  Match at end of text
# ---------------------------------------------------------------------------

def test_single_match_end():
    result = count_pattern("xyzabc", "abc")
    assert result == [3], f"expected [3], got {result}"


# ---------------------------------------------------------------------------
# 6  Multiple non-overlapping matches
# ---------------------------------------------------------------------------

def test_multiple_matches():
    result = count_pattern("abcabc", "abc")
    assert result == [0, 3], f"expected [0, 3], got {result}"


# ---------------------------------------------------------------------------
# 7  Overlapping matches
# ---------------------------------------------------------------------------

def test_overlapping_matches():
    # 'aaaa' contains 'aa' at positions 0, 1, 2
    result = count_pattern("aaaa", "aa")
    assert result == [0, 1, 2], f"expected [0,1,2], got {result}"

    # Classic KMP overlapping: 'aaaaaa' / 'aaa' → [0,1,2,3]
    result2 = count_pattern("aaaaaa", "aaa")
    assert result2 == _naive("aaaaaa", "aaa"), f"overlapping mismatch: {result2}"


# ---------------------------------------------------------------------------
# 8  Single wildcard '?' matches any character
# ---------------------------------------------------------------------------

def test_single_wildcard():
    result = count_pattern("abcabc", "a?c")
    assert result == [0, 3], f"expected [0, 3], got {result}"

    # '?' in middle
    result2 = count_pattern("aXbYc", "a?b")
    assert result2 == _naive("aXbYc", "a?b")

    # '?' at the start
    result3 = count_pattern("xyzxyz", "?yz")
    assert result3 == _naive("xyzxyz", "?yz")

    # '?' does NOT match zero chars
    assert count_pattern("ac", "a?c") == []


# ---------------------------------------------------------------------------
# 9  All-wildcard pattern matches exactly once at each valid position
# ---------------------------------------------------------------------------

def test_all_wildcard_pattern():
    # pattern '?????' has length 5, text 'hello' has length 5 → [0]
    result = count_pattern("hello", "?????")
    assert result == [0], f"expected [0], got {result}"

    # pattern '??' in 'abcd' → [0, 1, 2]
    result2 = count_pattern("abcd", "??")
    assert result2 == _naive("abcd", "??"), f"all-wildcard mismatch: {result2}"


# ---------------------------------------------------------------------------
# 10  Matches at both start and end
# ---------------------------------------------------------------------------

def test_match_start_and_end():
    result = count_pattern("abXYZab", "ab")
    assert result == [0, 5], f"expected [0, 5], got {result}"


# ---------------------------------------------------------------------------
# 11  Wildcard at boundaries of pattern
# ---------------------------------------------------------------------------

def test_wildcard_at_boundaries():
    # '?b?' matches any char + 'b' + any char
    text = "abcabcXbZ"
    result = count_pattern(text, "?b?")
    expected = _naive(text, "?b?")
    assert result == expected, f"wildcard boundary: {result} != {expected}"


# ---------------------------------------------------------------------------
# 12  Single character text and pattern
# ---------------------------------------------------------------------------

def test_single_char_text_and_pat():
    assert count_pattern("a", "a") == [0]
    assert count_pattern("a", "b") == []
    assert count_pattern("a", "?") == [0]


def test_special_chars_in_text():
    """'?' in the pattern matches ANY character in the text, including
    punctuation such as '#'. The contract does not restrict the alphabet, so a
    wildcard must match a literal '#' the same as any other character (a common
    sentinel-collision bug fails this)."""
    assert count_pattern("a##b", "a??b") == _naive("a##b", "a??b") == [0]
    assert count_pattern("x#y#z", "?#?") == _naive("x#y#z", "?#?")
    assert count_pattern("a#b#a#b", "a#b") == _naive("a#b#a#b", "a#b")


# ---------------------------------------------------------------------------
# 13  HARD adversarial complexity gate
#     text='a'*1_000_000, pattern='a'*499+'?'
#     Naive O(n*m) needs ~5e11 comparisons → times out.
#     KMP/Z-algo O(n+m) finishes in <1 second.
# ---------------------------------------------------------------------------

@pytest.mark.adversarial_complexity
def test_adversarial_complexity_gate():
    """Degenerate input that defeats naive O(n*m) backtracking."""
    K = 1_000_000
    m_pat = 499
    text = "a" * K
    pattern = "a" * m_pat + "?"
    # Must complete within 5 seconds; naive O(n*m) cannot.
    result = gu.run_within(5.0, count_pattern, text, pattern)
    # Verify correctness: pattern matches at every position 0..K-m_pat-1
    expected_len = K - (m_pat + 1) + 1  # = K - m_pat
    assert isinstance(result, list), "result must be a list"
    assert len(result) == expected_len, (
        f"expected {expected_len} matches, got {len(result)}"
    )
    assert result[0] == 0
    assert result[-1] == K - m_pat - 1


# ---------------------------------------------------------------------------
# 14  SOFT complexity signal (only fails if far worse than O(n))
# ---------------------------------------------------------------------------

@pytest.mark.soft_complexity
def test_soft_complexity():
    """Empirical time-complexity estimate — advisory; fails only if egregiously wrong."""
    import random
    import string
    import time

    # Measure time for count_pattern on text of varying lengths
    # Use a worst-case-ish pattern but keep sizes manageable
    sizes = [10_000, 20_000, 40_000, 80_000, 160_000]

    def make_input(n):
        rng = random.Random(n)
        text = "".join(rng.choices("ab", k=n))
        # pattern: 'a'*10 + '?' to exercise the wildcard path
        pattern = "a" * 10 + "?"
        return text, pattern

    timings = gu.measure_runtime(
        make_input,
        lambda pair: count_pattern(*pair),
        sizes,
        repeats=2,
    )
    report = gu.estimate_time_complexity(timings)
    label = report["label"]
    print(
        f"[soft_complexity] estimated={label}  target=O(n)  ranked={report['ranked'][:4]}"
    )
    # Allow up to O(n log n) — one tier above O(n) — before failing
    assert gu.within_one_tier(label, "O(n)"), (
        f"soft complexity check: estimated {label} is more than one tier above O(n). "
        "Likely an O(n*m) implementation; use KMP or Z-algorithm."
    )


# ---------------------------------------------------------------------------
# 15  Advisory code-quality report (never asserted)
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("case", _CORPUS["cases"], ids=range(len(_CORPUS["cases"])))
def test_mutation_corpus(case):
    """Replay the oracle-grounded, mutation-seeded corpus.

    Expected outputs come from Python's `re` engine (independent external oracle),
    cross-validated against the gold; each input discriminates a real wrong
    solution. A subtly-incorrect candidate that slips past the curated tests is
    caught here by an empirically-discovered killing input.
    """
    text, pattern = case["args"]
    assert count_pattern(text, pattern) == case["expected"]


@pytest.mark.code_quality
def test_code_quality():
    rep = gu.code_quality_report(SOL)
    print("code_quality:", rep)  # advisory only — never a gate
