"""Grader for competitive/cp02_profit_schedule. Tests the public contract only (see TASK.md).

Validity invariant: PASSES on the gold reference, FAILS on the broken reference.

Test catalogue (>=10 required for competitive):
  1.  test_empty                     — no jobs -> 0
  2.  test_single_positive           — one job -> its profit
  3.  test_single_negative           — negative profit -> 0 (skip it)
  4.  test_two_overlapping_pick_better — overlapping pair: take the higher-profit one
  5.  test_two_disjoint_pick_both    — non-overlapping pair: take both
  6.  test_adjacency_boundary        — job ending at t, next starting at t: compatible
  7.  test_negative_profit_skipped   — all negative -> 0
  8.  test_all_overlap_pick_max      — all mutually overlapping -> pick single best
  9.  test_three_jobs_chain          — chain of compatible jobs
  10. test_zero_profit_jobs          — zero-profit jobs; result still 0 or positive
  11. adversarial_greedy_fails       — crafted input where greedy-by-profit is strictly suboptimal
  12. adversarial_greedy_fails_v2    — second adversarial case (different structure)
  13. test_hard_complexity_gate      — n=100000 jobs, must complete within 5 seconds
  14. test_soft_complexity           — empirical curve; only fails >2 tiers off O(n log n)
  15. test_code_quality              — advisory only (never asserted)
"""
from __future__ import annotations

import json
import random
from pathlib import Path

import pytest

from _lib import grading_utils as gu

CATEGORY, TASK_ID = "competitive", "cp02_profit_schedule"
SOL = gu.require_solution_dir(CATEGORY, TASK_ID)
max_profit = gu.load_callable(SOL, "solution.py", "max_profit")

# Oracle-grounded mutation corpus (hidden under expected/, never shown to the
# agent). Every input's expected output was decided by an independent 2^n
# brute-force subset enumeration and verified equal to the gold; every input
# also kills >=1 real wrong solution (a mutation of the gold, a hand-written
# common mistake, or the __broken reference). Generated by
# experiment_mihaco/mutation_gen/gen_cp02_profit_schedule.py.
_CORPUS = json.loads(
    (Path(__file__).resolve().parents[1] / "expected" / "mutation_corpus.json").read_text()
)

# Fixed RNG for all generated data — grader must be deterministic.
_RNG = random.Random(42)


# ---------------------------------------------------------------------------
# 1  Empty input
# ---------------------------------------------------------------------------

def test_empty():
    assert max_profit([]) == 0


# ---------------------------------------------------------------------------
# 2  Single job (positive profit)
# ---------------------------------------------------------------------------

def test_single_positive():
    assert max_profit([(1, 5, 50)]) == 50


# ---------------------------------------------------------------------------
# 3  Single job (negative profit) — should be skipped
# ---------------------------------------------------------------------------

def test_single_negative():
    assert max_profit([(1, 5, -10)]) == 0


# ---------------------------------------------------------------------------
# 4  Two overlapping jobs — pick the better one
# ---------------------------------------------------------------------------

def test_two_overlapping_pick_better():
    # (1,4,30) and (3,6,60) overlap (3 < 4): pick max = 60
    assert max_profit([(1, 4, 30), (3, 6, 60)]) == 60


# ---------------------------------------------------------------------------
# 5  Two disjoint jobs — pick both
# ---------------------------------------------------------------------------

def test_two_disjoint_pick_both():
    # (1,3,30) and (5,8,40): fully disjoint
    assert max_profit([(1, 3, 30), (5, 8, 40)]) == 70


# ---------------------------------------------------------------------------
# 6  Adjacency boundary — end == start means COMPATIBLE (not conflicting)
# ---------------------------------------------------------------------------

def test_adjacency_boundary():
    # job A ends at 5, job B starts at 5: compatible -> pick both
    assert max_profit([(1, 5, 20), (5, 9, 30)]) == 50


# ---------------------------------------------------------------------------
# 7  All negative profits — pick nothing -> 0
# ---------------------------------------------------------------------------

def test_negative_profit_skipped():
    jobs = [(-5, 0, -1), (0, 3, -100), (2, 7, -50)]
    assert max_profit(jobs) == 0


# ---------------------------------------------------------------------------
# 8  All mutually overlapping — pick only the best single job
# ---------------------------------------------------------------------------

def test_all_overlap_pick_max():
    # All start at 0, end at 10 — any two conflict
    jobs = [(0, 10, 5), (0, 10, 20), (0, 10, 15)]
    assert max_profit(jobs) == 20


# ---------------------------------------------------------------------------
# 9  Chain of three compatible jobs
# ---------------------------------------------------------------------------

def test_three_jobs_chain():
    # (0,2,10), (2,5,15), (5,8,25) — all adjacent/compatible -> sum=50
    assert max_profit([(0, 2, 10), (2, 5, 15), (5, 8, 25)]) == 50


# ---------------------------------------------------------------------------
# 10  Mix of zero-profit and positive-profit jobs
# ---------------------------------------------------------------------------

def test_zero_profit_jobs():
    # Zero-profit jobs should neither help nor hurt; result = positive jobs
    jobs = [(0, 3, 0), (3, 6, 0), (0, 6, 10)]
    # (0,6,10) overlaps both zero-profit jobs; take it alone -> 10
    # OR take (0,3,0)+(3,6,0) -> 0
    assert max_profit(jobs) == 10


# ---------------------------------------------------------------------------
# 11  ADVERSARIAL: greedy-by-highest-profit is strictly suboptimal
#     One big job (profit=15) covers time [0,10].
#     Two medium jobs (profit=8 each) cover [0,5] and [5,10] respectively.
#     Greedy picks the big job (profit=15); DP picks both medium jobs (=16).
# ---------------------------------------------------------------------------

def test_adversarial_greedy_fails():
    jobs = [
        (0, 10, 15),   # high profit, covers whole range
        (0, 5,  8),    # medium, first half
        (5, 10, 8),    # medium, second half (compatible with above)
    ]
    # Correct answer: 8 + 8 = 16 (DP finds this)
    # Greedy-by-profit picks (0,10,15) first, then cannot add anything -> 15
    assert max_profit(jobs) == 16


# ---------------------------------------------------------------------------
# 12  ADVERSARIAL v2: deeper chain defeats greedy
#     One job (profit=20) covers [0,6].
#     Three jobs of profit=8 cover [0,2], [2,4], [4,6] respectively.
#     Greedy picks 20; DP picks 8+8+8=24.
# ---------------------------------------------------------------------------

def test_adversarial_greedy_fails_v2():
    jobs = [
        (0, 6, 20),   # high single job
        (0, 2,  8),
        (2, 4,  8),
        (4, 6,  8),
    ]
    # Correct: 8+8+8 = 24
    # Greedy: picks (0,6,20) then nothing else fits -> 20
    assert max_profit(jobs) == 24


# ---------------------------------------------------------------------------
# 13  HARD complexity gate: n=100000, must finish within 5 seconds
# ---------------------------------------------------------------------------

def test_hard_complexity_gate():
    """n=100 000 jobs — O(n log n) solution finishes; O(n^2) does not."""
    rng = random.Random(42)
    n = 100_000
    jobs = []
    t = 0
    for _ in range(n):
        start = t + rng.randint(0, 3)
        end = start + rng.randint(1, 10)
        profit = rng.randint(-5, 100)
        jobs.append((start, end, profit))
        t = start  # allow overlaps: next job may start before current ends

    result = gu.run_within(5.0, max_profit, jobs)
    assert isinstance(result, int)
    assert result >= 0


# ---------------------------------------------------------------------------
# 14  SOFT complexity signal (only fails if >2 tiers worse than O(n log n))
# ---------------------------------------------------------------------------

@pytest.mark.soft_complexity
def test_soft_complexity():
    """Empirical time-complexity estimate — advisory; only fails if egregiously wrong."""
    sizes = [500, 1000, 2000, 4000, 8000, 16000]

    def make_input(n):
        rng = random.Random(n)
        jobs = []
        t = 0
        for _ in range(n):
            start = t + rng.randint(0, 3)
            end = start + rng.randint(1, 10)
            profit = rng.randint(1, 100)
            jobs.append((start, end, profit))
            t = start
        return (jobs,)

    timings = gu.measure_runtime(make_input, lambda args: max_profit(*args), sizes)
    report = gu.estimate_time_complexity(timings)
    label = report["label"]
    print(f"[soft_complexity] estimated={label}  target=O(n log n)  ranked={report['ranked'][:3]}")
    # Allow up to one tier worse than O(n log n) — O(n^2) would be 2 tiers off
    assert gu.within_one_tier(label, "O(n log n)"), (
        f"soft complexity check: estimated {label} is more than one tier above O(n log n). "
        "This strongly suggests an O(n^2) or worse algorithm."
    )


# ---------------------------------------------------------------------------
# Mutation corpus — oracle-grounded, mutation-seeded
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("case", _CORPUS["cases"], ids=range(len(_CORPUS["cases"])))
def test_mutation_corpus(case):
    """Replay the oracle-grounded, mutation-seeded corpus.

    Expected outputs come from an independent 2^n brute-force subset
    enumeration, cross-validated against the gold; each input discriminates a
    real wrong solution. A subtly-incorrect candidate that slips past the
    curated tests above is caught here by an empirically-discovered killing
    input.

    JSON turns tuples into lists — convert each job back to a tuple.
    """
    jobs = [tuple(j) for j in case["args"][0]]
    assert max_profit(jobs) == case["expected"]


# ---------------------------------------------------------------------------
# 15  Advisory code-quality report (never asserted)
# ---------------------------------------------------------------------------

@pytest.mark.code_quality
def test_code_quality():
    rep = gu.code_quality_report(SOL)
    print("code_quality:", rep)   # advisory only — never a gate
